public enum NumberName
{
    None = 0,
    K = 3,       // Thousand
    M = 6,       // Million
    B = 9,       // Billion
    T = 12,      // Trillion
    Qa = 15,     // Quadrillion
    Qi = 18,     // Quintillion
    Se = 21,     // Sextillion
    Sp = 24,     // Septillion
    Oc = 27,     // Octillion
    No = 30,     // Nonillion
    De = 33,     // Decillion
    Ud = 36,     // Undecillion
    Du = 39,     // Duodecillion
    Td = 42,     // Tredecillion
    Qad = 45,    // Quattuordecillion
    Qid = 48,    // Quindecillion
    Sed = 51,    // Sexdecillion
    Spd = 54,    // Septendecillion
    Ocd = 57,    // Octodecillion
    Nod = 60,    // Novemdecillion
    Vig = 63,    // Vigintillion
    Uv = 66,     // Unvigintillion
    Dv = 69,     // Duovigintillion
    Tv = 72,     // Tresvigintillion
    Qav = 75,    // Quattuorvigintillion
    Qiv = 78,    // Quinvigintillion
    Sev = 81,    // Sesvigintillion
    Spv = 84,    // Septenvigintillion
    Ocv = 87,    // Octovigintillion
    Nov = 90,    // Novemvigintillion
    Trg = 93,    // Trigintillion
    Ut = 96,     // Untrigintillion
    Dt = 99,     // Duotrigintillion
    Tt = 102,    // Trestrigintillion
    Qat = 105,   // Quattuortrigintillion
    Qit = 108,   // Quintrigintillion
    Set = 111,   // Sestrigintillion
    Spt = 114,   // Septentrigintillion
    Oct = 117,   // Octotrigintillion
    Not = 120    // Novemtrigintillion
}